FROM postgres:17

# Configuració de variables d'entorn per a PostgreSQL
ENV POSTGRES_USER tamarro_user
ENV POSTGRES_PASSWORD tamarro_password
ENV POSTGRES_DB tamarro_db

# Variables per a configuració del motor PostgreSQL
ENV PGDATA /var/lib/postgresql/data

# Copiar el nostre script d'inicialització
COPY db/init.db /docker-entrypoint-initdb.d/init.sql

# Exposar el port estàndard de PostgreSQL
EXPOSE 5432